CREATE SEQUENCE "SEQ_AIR_MONITORING_DEVICE_ID"
    START WITH 1
    NOCACHE
    NOCYCLE;

CREATE TABLE devices (
    "ID" INTEGER,
    "MODEL" VARCHAR2(50),
    "STATUS" VARCHAR2(20)
    );

ALTER TABLE devices
ADD (
CONSTRAINT pk_devices PRIMARY KEY ("ID"),
CHECK ("STATUS" IN ('ACTIVE','HEATING_UP','INACTIVE'))
);