CREATE TABLE air_quality_sensors (
    "DEVICE_ID" INTEGER DEFAULT SEQ_AIR_MONITORING_DEVICE_ID.nextval,
    "MODEL" VARCHAR2(30),
    "STATUS" VARCHAR2(30),
    "SITE" VARCHAR2(30),
    "AQI" NUMBER,
    "TEMPERATURE_CELSIUS" NUMBER,
    "HUMIDITY_PERCENTAGE" NUMBER,
    "ECO2_PPM" NUMBER,
    "TVOC_PPB" NUMBER
    );

ALTER TABLE air_quality_sensors
ADD (
CONSTRAINT pk_air_quality_sensors PRIMARY KEY ("DEVICE_ID"),
CONSTRAINT fk_air_quality_sensors_devices FOREIGN KEY ("DEVICE_ID") REFERENCES devices("DEVICE_ID")
);

CREATE TABLE gas_leak_detectors (
    "DEVICE_ID" INTEGER DEFAULT SEQ_AIR_MONITORING_DEVICE_ID.nextval,
    "MODEL" VARCHAR2(30),
    "STATUS" VARCHAR2(30),
    "SITE" VARCHAR2(30),
    "CO2_PPM" NUMBER,
    "HC_PPM" NUMBER,
    "CH4_PPM" NUMBER,
    "CO_PPM" NUMBER,
    "N2O_PPM" NUMBER,
    "NH3_PPM" NUMBER,
    "NO_PPM" NUMBER
    );

ALTER TABLE gas_leak_detectors
ADD (
CONSTRAINT pk_gas_leak_detectors PRIMARY KEY ("DEVICE_ID"),
CONSTRAINT fk_gas_leak_detectors_devices FOREIGN KEY ("DEVICE_ID") REFERENCES devices("DEVICE_ID")
);

CREATE TABLE ozone_monitoring_instruments (
    "DEVICE_ID" INTEGER DEFAULT SEQ_AIR_MONITORING_DEVICE_ID.nextval,
    "MODEL" VARCHAR2(30),
    "STATUS" VARCHAR2(30),
    "AREA" VARCHAR2(30),
    "ORBIT_HEIGHT_KM" NUMBER,
    "NO2_10E15_MOLECULES_CM_2" NUMBER,
    "SO2_10E15_MOLECULES_CM_2" NUMBER,
    "BRO_10E15_MOLECULES_CM_2" NUMBER,
    "HCHO_10E15_MOLECULES_CM_2" NUMBER,
    "AEROSOL_AOD" NUMBER
    );

ALTER TABLE ozone_monitoring_instruments
ADD (
CONSTRAINT pk_ozone_monitoring_instruments PRIMARY KEY ("DEVICE_ID"),
CONSTRAINT fk_ozone_monitoring_instruments_devices FOREIGN KEY ("DEVICE_ID") REFERENCES devices("DEVICE_ID")
);